/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ContactSubmission = {
  _id: string;
  _type: "contactSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  message?: string;
  submittedAt?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  organization?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  type?: "work" | "education";
  startDate?: string;
  endDate?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  summary?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  techStack?: Array<string>;
  repoUrl?: string;
  liveUrl?: string;
  showOnSite?: boolean;
  featured?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  about?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  resumeFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  skillCategories?: Array<
    {
      _key: string;
    } & SkillCategory
  >;
  appearance?: Appearance;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    favicon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Appearance = {
  _type: "appearance";
  activeTheme?: "minimal" | "professional";
  minimal?: ThemeColors;
  professional?: ThemeColors;
  cursorGlowEnabled?: boolean;
};

export type ThemeColors = {
  _type: "themeColors";
  background?: string;
  text?: string;
  accent?: string;
};

export type SkillCategory = {
  _type: "skillCategory";
  name?: string;
  skills?: Array<
    {
      _key: string;
    } & Skill
  >;
};

export type Skill = {
  _type: "skill";
  name?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "github" | "linkedin" | "twitter" | "email" | "other";
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ContactSubmission
  | SanityImageAssetReference
  | Experience
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | SanityFileAssetReference
  | SiteSettings
  | Appearance
  | ThemeColors
  | SkillCategory
  | Skill
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    name,    title,    about,    profileImage{      asset->{_id, url, metadata{lqip, dimensions{width, height}}},      alt,      hotspot,      crop    },    resumeFile{      asset->{_id, url, originalFilename}    },    socialLinks[]{_key, platform, url},    skillCategories[]{      _key,      name,      skills[]{        _key,        name,        icon{asset->{_id, url}, alt}      }    },    appearance{      activeTheme,      minimal{background, text, accent},      professional{background, text, accent},      cursorGlowEnabled    },    seo{      title,      description,      ogImage{asset->{_id, url}},      favicon{asset->{_id, url}}    }  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      name: null;
      title: null;
      about: null;
      profileImage: null;
      resumeFile: null;
      socialLinks: null;
      skillCategories: null;
      appearance: null;
      seo: null;
    }
  | {
      name: null;
      title: string | null;
      about: null;
      profileImage: null;
      resumeFile: null;
      socialLinks: null;
      skillCategories: null;
      appearance: null;
      seo: null;
    }
  | {
      name: string | null;
      title: null;
      about: null;
      profileImage: null;
      resumeFile: null;
      socialLinks: null;
      skillCategories: null;
      appearance: null;
      seo: null;
    }
  | {
      name: string | null;
      title: string | null;
      about: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      profileImage: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      resumeFile: {
        asset: {
          _id: string;
          url: string | null;
          originalFilename: string | null;
        } | null;
      } | null;
      socialLinks: Array<{
        _key: string;
        platform: "email" | "github" | "linkedin" | "other" | "twitter" | null;
        url: string | null;
      }> | null;
      skillCategories: Array<{
        _key: string;
        name: string | null;
        skills: Array<{
          _key: string;
          name: string | null;
          icon: {
            asset: {
              _id: string;
              url: string | null;
            } | null;
            alt: string | null;
          } | null;
        }> | null;
      }> | null;
      appearance: {
        activeTheme: "minimal" | "professional" | null;
        minimal: {
          background: string | null;
          text: string | null;
          accent: string | null;
        } | null;
        professional: {
          background: string | null;
          text: string | null;
          accent: string | null;
        } | null;
        cursorGlowEnabled: boolean | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        ogImage: {
          asset: {
            _id: string;
            url: string | null;
          } | null;
        } | null;
        favicon: {
          asset: {
            _id: string;
            url: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && showOnSite != false] | order(featured desc, order asc, _createdAt desc){    _id,    title,    "slug": slug.current,    coverImage{      asset->{_id, url, metadata{lqip, dimensions{width, height}}},      alt,      hotspot,      crop    },    summary,    techStack,    repoUrl,    liveUrl,    featured,    "hasCaseStudy": defined(body) && length(body) > 0  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  summary: string | null;
  techStack: Array<string> | null;
  repoUrl: string | null;
  liveUrl: string | null;
  featured: boolean | null;
  hasCaseStudy: boolean | false | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug && showOnSite != false][0]{    _id,    title,    "slug": slug.current,    coverImage{      asset->{_id, url, metadata{lqip, dimensions{width, height}}},      alt,      hotspot,      crop    },    gallery[]{      _key,      asset->{_id, url, metadata{lqip, dimensions{width, height}}},      alt,      hotspot,      crop    },    summary,    body,    techStack,    repoUrl,    liveUrl  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  gallery: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  summary: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  techStack: Array<string> | null;
  repoUrl: string | null;
  liveUrl: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current) && showOnSite != false]{"slug": slug.current}
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc, order asc){    _id,    role,    organization,    logo{asset->{_id, url}},    type,    startDate,    endDate,    description  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  role: string | null;
  organization: string | null;
  logo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  type: "education" | "work" | null;
  startDate: string | null;
  endDate: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    name,\n    title,\n    about,\n    profileImage{\n      asset->{_id, url, metadata{lqip, dimensions{width, height}}},\n      alt,\n      hotspot,\n      crop\n    },\n    resumeFile{\n      asset->{_id, url, originalFilename}\n    },\n    socialLinks[]{_key, platform, url},\n    skillCategories[]{\n      _key,\n      name,\n      skills[]{\n        _key,\n        name,\n        icon{asset->{_id, url}, alt}\n      }\n    },\n    appearance{\n      activeTheme,\n      minimal{background, text, accent},\n      professional{background, text, accent},\n      cursorGlowEnabled\n    },\n    seo{\n      title,\n      description,\n      ogImage{asset->{_id, url}},\n      favicon{asset->{_id, url}}\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current) && showOnSite != false] | order(featured desc, order asc, _createdAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage{\n      asset->{_id, url, metadata{lqip, dimensions{width, height}}},\n      alt,\n      hotspot,\n      crop\n    },\n    summary,\n    techStack,\n    repoUrl,\n    liveUrl,\n    featured,\n    "hasCaseStudy": defined(body) && length(body) > 0\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug && showOnSite != false][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage{\n      asset->{_id, url, metadata{lqip, dimensions{width, height}}},\n      alt,\n      hotspot,\n      crop\n    },\n    gallery[]{\n      _key,\n      asset->{_id, url, metadata{lqip, dimensions{width, height}}},\n      alt,\n      hotspot,\n      crop\n    },\n    summary,\n    body,\n    techStack,\n    repoUrl,\n    liveUrl\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current) && showOnSite != false]{"slug": slug.current}\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(startDate desc, order asc){\n    _id,\n    role,\n    organization,\n    logo{asset->{_id, url}},\n    type,\n    startDate,\n    endDate,\n    description\n  }\n': EXPERIENCE_QUERY_RESULT;
  }
}
